# Install packages
install.packages("jsonlite")
install.packages("geosphere")
install.packages("dplyr")
install.packages("readr")
install.packages("lubridate")
install.packages("tidytext")
install.packages("textdata")
install.packages("ggplot2")
install.packages("syuzhet")
install.packages("tidyr")
install.packages("fixest")
install.packages("broom")
install.packages("purrr")
install.packages("stringr")
install.packages("kableExtra")

# Read packages
library(jsonlite)
library(geosphere)
library(dplyr)
library(readr)
library(lubridate)
library(tidytext)
library(textdata)
library(ggplot2)
library(tidyr)
library(fixest)
library(broom)
library(purrr)
library(stringr)
library(knitr)
library(kableExtra)

# Read JSON dataset
#con <- file("yelp_academic_dataset_business.json", "r")
#full_business <- stream_in(con)
#con_review <- file("yelp_academic_dataset_review.json", "r")
#full_review <- stream_in(con_review)